### PR TITLE
DOCUMENTATION - ADDING CONTRIBUTING FILE , IMPROVE IT 

### LINKED ISSUE #1: DOCUMENTATION -  ADDING CONTRIBUTING FILE , IMPROVE IT
Hi @sharmaumang001 

I found there is no CONTRIBUTING file in this repository 
I would be glad to work on it 

Kindly do assign me 

I can add a great contributing file with all contributing guidlines in it 
Kindly do add the DWOC  and Level label

### PR DESCRIPTION
**Pull request by akrish4**
#### Issue Number
ISSUE #1
Fixed : #1 

#### Describe the changes you've made
Updated README 
Added Screenshots 
Added Libraires used
Added Contributors
Added Contributing.md file 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA 

#### Additional context (OPTIONAL)
NA 

#### Test plan (OPTIONAL)
NA 
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CODE OF CONDUCT](https://github.com/sharmaumang001/Mobile-Brower/blob/master/CODE_OF_CONDUCT.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Participating in SWOC2021.
- [x] Participating in DWOC.

### CODE REVIEW

**Comment by akrish4** [comment]
Hi @sharmaumang001 
Kindly do check and merge it 
Kindly do add the same labels (DWOC and Level-2 label ) 
If this project is registered for SWOC , then kindly add SWOC and easy label also

**Comment by sharmaumang001** [comment]
Changes.

I have not used the libraries decribed ( i asked you to take idea from that repo , not copy..)

-Please open the project nd then list then libraries 

-I saw you removed code of conduct file from readme for Adding contributing.md(re add code of conduct in some othee section )

-Te avatars of contributor looks hard coded, what if a new contributor comes in? Will it update on its own.?

**Comment by akrish4** [comment]
> Changes.
> 
> I have not used the libraries decribed ( i asked you to take idea from that repo , not copy..)
> 
> -Please open the project nd then list then libraries
> 
> -I saw you removed code of conduct file from readme for Adding contributing.md(re add code of conduct in some othee section )
> 
> -Te avatars of contributor looks hard coded, what if a new contributor comes in? Will it update on its own.?

I am not aware of the libraries since i don't know android development , I have just updated readme , it would be better if you or someone who is aware of kotlin and java and update the libraires , I don't even know how to run it , so pls change it , if you can tell me the libraries used m i can add the same 

code of conduct link is already added in the just above line of the contributing file , if you want to make it re add i will add 

yes the avatars are hardcoded , it won't update on itsown , for updating by its own , you have to install a bot for that , that is @all-contributors bot , whenever a new contribuor comes in , ask them to update the contributors table by adding their name till the bot is installed

**Comment by sharmaumang001** [comment]
Do one thing , comment out the libraries used section 
We will update it later on

Contributing nd COC is fine

Also remove all contributors list ( we will add bot later on)
In place of that ( About the owner or connect with the owner) or author jo bhi hota.

Put my My LinkedIn || My website || My twitter 

https://www.linkedin.com/in/0729

Find other two on my GitHub profile ,

Then create PR. I will merge

**Comment by akrish4** [comment]
I have updated according to what you said , all done 
Kindly do merge it and also add the same labels

**Comment by akrish4** [comment]
@sharmaumang001  I have updated it , kindly check and merge it

**Comment by akrish4** [comment]
pls add the labels that are added in the issue 
@sharmaumang001 
ie ( DWOC and Level-2) labels in pr too

**Comment by akrish4** [comment]
@sharmaumang001  
pls add the labels that are added in the issue
ie ( DWOC and Level-2) labels in pr too

**Pull request merged**
