### PR TITLE
History UI update

### LINKED ISSUE #15: IMPROVE OVERALL UI

### PR DESCRIPTION
**Pull request by Manoj-Paramsetti**
#### Issue Number
ISSUE #28

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CODE OF CONDUCT](https://github.com/sharmaumang001/Mobile-Brower/blob/master/CODE_OF_CONDUCT.md)** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Participating in SWOC2021.
- [x] Participating in DWOC.

### CODE REVIEW

**Comment by sharmaumang001** [comment]
Add other UI changes too!

**Comment by Manoj-Paramsetti** [comment]
Okay! I'll do that...

**Comment by sharmaumang001** [comment]
@Manoj-Paramsetti upstream your project and create another PR

**Comment by sharmaumang001** [comment]
Please upstream the project and create another PR.
Also try to solve if there are any conflicts left after that.
For help text in channel on discord

**Pull request closed without merging**
