### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by Manoj-Paramsetti**
#### Issue Number
ISSUE # 27

#### Describe the changes you've made
I made a UI update on history and added some cool font to enhance UX

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Updated History UI
#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CODE OF CONDUCT](https://github.com/sharmaumang001/Mobile-Brower/blob/master/CODE_OF_CONDUCT.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Participating in SWOC2021.
- [x] Participating in DWOC.

### CODE REVIEW

**Comment by sharmaumang001** [comment]
Add the screenshots of the UI changes

**Comment by Manoj-Paramsetti** [comment]
Screenshot from 2021-01-29 14-13-36

**Comment by Manoj-Paramsetti** [comment]
I changed the font in the history activity
Updated the clear history button background
I made some improvements and corrected the constraint values
Added some white space go to enhance the look

**Comment by sharmaumang001** [comment]
Hey there your PR contains a lot of conflicts, Do solve them and then create aPR
Moreover , Do more changes to other fragments or activities at least 3-4 so that I can give a proper level 3.

**Comment by sharmaumang001** [comment]
Your conflicts might get solved by updating the projects 
As git ignore was added later On.

**Comment by Manoj-Paramsetti** [comment]
Okay I'll  try to rebase it

**Pull request closed without merging**
